.TH "COSMA" "" "January 2022" "" ""
.SH "NAME"
\fBCosma\fR
.QP
.P
Cosma \- Cosma is a document graph visualization tool\.

.
.SH SYNOPSIS
.P
\fBcosma  [config]  [c]  [record]  [r]  [autorecord]  [a]  [batchrecord]  [b]  [modelize]  [m]  [\-\-citeproc]  [\-c]  [\-\-publish]  [\-p]  [\-\-load_css_custom]  [\-css]  [\-\-files_origin]  [\-f]  [\-\-export_target]  [\-e]  [\-\-lang]  [\-l]  [\-\-history]  [\-h]  [\-\-save]  [\-s]\fP
.SH EXAMPLES
.P
\fBcosma autorecord "my note" "idea", "tag 1,tag2"\fP
.P
\fBcosma m \-p \-c \-css\fP
.P
\fBcosma b "\./records\.json"\fP
.SH OPTIONS
.P
\fBconfig\fP, \fBc\fP
    Generate a template configuration file
.P
\fBrecord\fP, \fBr\fP
    Create a record (form mode)
.P
\fBautorecord\fP, \fBa\fP
    Create a record (oneliner)
.P
\fBbatchrecord\fP, \fBb\fP
    Create a series of records
.P
\fBmodelize\fP, \fBm\fP
    Generate a cosmoscope (visualization)
.P
\fBmodelize \-\-citeproc\fP, \fBm \-c\fP
    Generate a cosmoscope with quoting
.P
\fBmodelize \-\-load_css_custom\fP, \fBm \-css\fP
    Generate a cosmoscope with custom CSS
.P
\fBmodelize \-\-files_origin\fP, \fBm \-f\fP
    Generate a cosmoscope from a directory
.P
\fBmodelize \-\-export_target\fP, \fBm \-e\fP
    Generate a cosmoscope to a directory
.P
\fBmodelize \-\-lang\fP, \fBm \-l\fP
    Generate a cosmoscope to a directory
.P
\fBmodelize \-\-history\fP, \fBm \-h\fP
    Save the cosmoscope to history
.P
\fBmodelize \-\-save\fP, \fBm \-s\fP
    Save options to the config file
.SH LICENSE
.P
ANR HyperOtlet, GPL\-3\.0 License\.

